[tool.poetry]
name = "geneci"
version = "1.0.0"
description = ""
authors = ["\"Ryan Sanchez\""]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.0"
filelock = "^3.15.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
